# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'nutritionTracker' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for nutritionTracker

  pod 'GoogleMobileVision/FaceDetector'
  pod 'GoogleAPIClientForREST/Calendar', '~> 1.2.1'
  pod 'Google/SignIn', '~> 3.0.3'

end
